services:
  mongo-db:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/

  dbgate:
    image: dbgate/dbgate
    container_name: dbgate
    restart: unless-stopped
    depends_on:
      - mongo-db
    ports:
      - 8080:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1

      LABEL_con1: MongoDB
      URL_con1: mongodb://root:example@mongodb:27017/?authSource=admin # notice it's the same as your container name
      ENGINE_con1: mongo@dbgate-plugin-mongo

volumes:
  db-data:
  dbgate-data:
